reverted pull-request.yml and fixed node.js.yml

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -9,11 +9,9 @@ jobs:
   validate:
     runs-on: ubuntu-latest
     steps:
-      - name: Check if current branch is pre-deploy
+      - name: Check source branch
         run: |
-          if [[ "${{ github.event.pull_request.head.ref }}" == "pre-deploy" ]]; then
-            if [[ "${{ github.event.pull_request.base }}" != "main" ]] then
-              echo "Error: Pull requests to 'main' must originate from 'pre-deploy' branch."
-              exit 1
-            fi
+          if [[ "${{ github.head_ref }}" != "pre-deploy" ]]; then
+            echo "Error: Pull requests to 'main' must originate from 'pre-deploy' branch."
+            exit 1
           fi
